Restructure code
apurata/woocommerce-acuotaz-payment-gateway pull request #6
Opened 2021-01-22 16:29 UTC by andyapurata

2021-01-25 23:06 UTC, vanesant01 approved these changes

2021-01-26 16:21 UTC, quique0194 requested changes

2021-01-26 16:21 UTC, quique0194 commented on readme.txt
> +Requires at least: 5.3.2
por qué le subiste el wordpress? hay que probar con 4.2.0

2021-01-26 16:21 UTC, quique0194 commented on create_release.sh
> +	cp -r includes ${PLUGIN_NAME}
includes es un buen nombre para lo que importas? es masomenos standard?

2021-01-26 18:56 UTC, merged